/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MIGUELITO
 */
public class PantallaConversor extends javax.swing.JFrame {
    
    //variable
    double valor;
    
    public PantallaConversor() {
        initComponents();
        //centrar pantalla
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cantidad = new javax.swing.JTextField();
        cambiopais1 = new javax.swing.JComboBox<>();
        cambiopais2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultado = new javax.swing.JTextArea();
        buttonconversor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cantidad.setBackground(new java.awt.Color(102, 153, 255));
        cantidad.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N

        cambiopais1.setBackground(new java.awt.Color(204, 255, 255));
        cambiopais1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cambiopais1.setForeground(new java.awt.Color(102, 0, 102));
        cambiopais1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SOL-Peru", "EE.UU-Dolar", "EUR-Euro", "GBP-LibraEsterliana", "JPY-YenJapones", "KRW-SurCoreano" }));
        cambiopais1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiopais1ActionPerformed(evt);
            }
        });

        cambiopais2.setBackground(new java.awt.Color(204, 255, 255));
        cambiopais2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cambiopais2.setForeground(new java.awt.Color(153, 0, 153));
        cambiopais2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SOL-Peru", "EE.UU-Dolar", "EUR-Euro", "GBP-LibraEsterliana", "JPY-YenJapones", "KRW-SurCoreano" }));

        resultado.setBackground(new java.awt.Color(255, 204, 255));
        resultado.setColumns(20);
        resultado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        resultado.setForeground(new java.awt.Color(0, 0, 255));
        resultado.setRows(5);
        jScrollPane1.setViewportView(resultado);

        buttonconversor.setBackground(new java.awt.Color(248, 229, 229));
        buttonconversor.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        buttonconversor.setForeground(new java.awt.Color(255, 0, 51));
        buttonconversor.setText("CONVERTIR");
        buttonconversor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonconversorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("CONVERSOR DE MONEDAS");

        salir.setBackground(new java.awt.Color(0, 0, 0));
        salir.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        salir.setForeground(new java.awt.Color(204, 0, 0));
        salir.setText("SALIR");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setForeground(new java.awt.Color(102, 0, 255));
        jButton1.setText("IR CONVERSOR DE MASA");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cambiopais2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(salir)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(146, 146, 146)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cambiopais1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(56, 56, 56))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(78, 78, 78)
                                    .addComponent(jButton1)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(buttonconversor)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cambiopais1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(buttonconversor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cambiopais2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonconversorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonconversorActionPerformed
      
        //donde se ingresa el valor "estamos captando el texfrind"
       valor = Double.parseDouble(cantidad.getText());
       
       //combox vox
       int combo1 = cambiopais1.getSelectedIndex(); //devuelve arreglos
       int combo2 = cambiopais2.getSelectedIndex();
       
       //puente coneccion de variables y metodos
       LogicaCodigo puente = new LogicaCodigo();
       puente.setValor(valor);
       puente.setCombo1(combo1);
       puente.setCombo2(combo2);
       
       //ejecucion de todos los metodos
       //conversion de soles/5paises
       double dolar = puente.SolesDolares();
       double eur = puente.SolesEuros();
       double gbp = puente.Soleslibra();
       double jpy = puente.solesyen();
       double krw = puente.Soleswon();
       
          //borrar al ejecutar otro resultado
       resultado.setText(" ");
       resultado.append("" + Math.round(dolar));  //se muestra el resultado
        
        
        resultado.setText(" ");
        resultado.append ("" + eur);
          
        resultado.setText(" ");
        resultado.append("" + gbp);
          
          
        resultado.setText(" ");
        resultado.append("" + jpy);
          
          
        resultado.setText(" ");
        resultado.append("" + krw);
         
       
       //conversion de dolares/4paises
       double eurr = puente.DolaresEur();
       double libra = puente.DolaresLibra();
       double yen = puente.DolarYen();
       double won = puente.DolarWon();
       
          //borrar al ejecutar otro resultado
       resultado.setText(" ");
       resultado.append("" + eurr);  //se muestra el resultado
        
        
        resultado.setText(" ");
        resultado.append ("" + libra);
          
        resultado.setText(" ");
        resultado.append("" + yen);
          
          
        resultado.setText(" ");
        resultado.append("" + won);
          
          
        //conversion de euros/3paises
        
        double libra3 = puente.EurLibra();
        double yen3 = puente.EurYen();
        double won3 = puente.EurWon();
        
               //borrar al ejecutar otro resultado
       resultado.setText(" ");
       resultado.append("" + libra3);  //se muestra el resultado
        
        
        resultado.setText(" ");
        resultado.append ("" + yen3);
          
        resultado.setText(" ");
        resultado.append("" + won3);
          
        //conversion de libra a 2paises
        double yen4 = puente.LibraYen();
        double won4 = puente.LibraWon();
        
                   //borrar al ejecutar otro resultado
       resultado.setText(" ");
       resultado.append("" + yen4);  //se muestra el resultado
        
        
        resultado.setText(" ");
        resultado.append ("" + won4);
        
        
        //convertir de yen/won
        
        double won5 = puente.YenWon();
        
                        //borrar al ejecutar otro resultado
       resultado.setText(" ");
       resultado.append("" + won5);  //se muestra el resultado
        
          
       
               
       
       
    
         
        
    }//GEN-LAST:event_buttonconversorActionPerformed

    private void cambiopais1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiopais1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cambiopais1ActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(WIDTH);
    }//GEN-LAST:event_salirActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        ingresar principal = new ingresar();
         principal.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           PantallaMasa ventanaMasa = new PantallaMasa();
         ventanaMasa.setVisible(true);
         this.dispose();//poner aqui
     
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaConversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaConversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaConversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaConversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaConversor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonconversor;
    private javax.swing.JComboBox<String> cambiopais1;
    private javax.swing.JComboBox<String> cambiopais2;
    private javax.swing.JTextField cantidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resultado;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables

    private void center() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private static class ingresar {

        public ingresar() {
        }

        private void setVisible(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    }
}
